CREATE TYPE category AS ENUM ('ROOM', 'HOUSE', 'FLAT', 'APARTMENT', 'HOTEL', 'MOTEL');
CREATE TYPE accommodation_change_type AS ENUM ('CREATED', 'UPDATED', 'DELETED');
CREATE TYPE reservation_status AS ENUM ('CREATED', 'CANCELED', 'FINISHED');
CREATE TYPE role AS ENUM ('USER', 'HOST');

CREATE TABLE app_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255),
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE,
    role                       role
);

CREATE TABLE country
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    continent VARCHAR(255) NOT NULL
);

CREATE TABLE host_profile
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id    BIGINT REFERENCES country (id),
    user_username VARCHAR(255) UNIQUE REFERENCES app_users (username)
);

CREATE TABLE accommodation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    category        category,
    host_profile_id BIGINT REFERENCES host_profile (id),
    num_rooms       INT,
    is_rented       BOOLEAN
);

CREATE TABLE review
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment          TEXT,
    rating           INT,
    accommodation_id BIGINT REFERENCES accommodation (id)
);

CREATE TABLE reservation_cart
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_created  TIMESTAMP,
    user_username VARCHAR(255) REFERENCES app_users (username),
    status        reservation_status
);

CREATE TABLE reservation_cart_accommodations
(
    reservation_cart_id BIGINT REFERENCES reservation_cart (id),
    accommodation_id    BIGINT REFERENCES accommodation (id),
    PRIMARY KEY (reservation_cart_id, accommodation_id)
);

CREATE TABLE accommodation_history
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accommodation_id BIGINT,
    name             VARCHAR(255),
    change_type      accommodation_change_type,
    timestamp        TIMESTAMP
);

create index idx_cart_user_status on reservation_cart (user_username, status);
create index idx_user_username_password on app_users (username, password);
create index idx_user_username on app_users (username);
create index idx_user_role on app_users (role);
