apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: accommodation
data:
  SPRING_PROFILES_ACTIVE: "${SPRING_PROFILE}"
  FRONTEND_HOST: "${FRONTEND_HOST}"
  FRONTEND_PORT: "${FRONTEND_PORT}"
  DB_PORT: "${POSTGRES_PORT}"
  BACKEND_PORT: "${BACKEND_PORT}"
