apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dummy/backend:latest
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: spring_profile
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DB_PORT
            - name: FRONTEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: FRONTEND_HOST
            - name: FRONTEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: FRONTEND_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: SECRET_KEY
