resources:
  - namespace.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - deployment-backend.yaml
  - service-backend.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - ingress.yaml
