apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-key
type: Opaque
stringData:
  SECRET_KEY: "${SECRET_KEY}"
